<?php

return [
    'update_timetable'  => 'Aktualizace Harmonogram',
    'updated'           => 'Aktualizováno',
    'upload'            => 'Nahrávání',
    'upload_file'       => 'Nahrát Soubor',
    'upload_logo'       => 'Nahrát Logo',
    'upload_result'     => 'Nahrát Výsledky',
    'upper_limit'       => 'Horní Limit',
    'url'               => 'URL',
    'use_mailgun'       => 'Použití Mailgun',
    'use_smtp'          => 'Použít SMTP',
    'use_sparkpost'     => 'Použití Sparkpost',
    'user_access'       => 'Přístup A Oprávnění',
    'user_create_event' => 'Přidán nový uživatel identifikován :email',
    'user_created'      => 'Uživatelský účet byl vytvořen',
    'user_roles'        => 'Uživatelské Role',
    'userame'           => 'Uživatelské jméno',
    'username'          => 'Uživatelské jméno',
    'username_email'    => 'Uživatelské jméno nebo E-mail',
    'users'             => 'Uživatelé',
    'verdict'           => 'Verdikt',
    'view'              => 'Zobrazit',
    'view_attendance'   => 'Zobrazit Docházky',
    'view_payments'     => 'Zobrazení Plateb',
    'view_profile'      => 'Zobrazit Profil',
    'view_results'      => 'Zobrazit Výsledky',
    'view_students'     => 'Pohled Studentů',
    'view_subjects'     => 'Zobrazení Předmětů',
    'view_timetable'    => 'Zobrazit Harmonogram',
    'weeks'             => ':n Týdnů',
    'with_rooms'        => 'S Pokoje',
    'year'              => 'Rok',
    'year_of_pub'       => 'Rok Vydání',
    'yearly_overview'   => 'Roční Přehled',
    'years'             => ':n Let',
    'yes'               => 'Ano',
    'yes_continue'      => 'Ano I Nadále',
    'your_f_name'       => 'Student je První Jméno',
    'your_l_name'       => 'Student příjmení',
    'your_marks'        => 'Marek Dosaženo pro',
    'your_sir_name'     => 'Student Příjmení',
];
