<?php

return [
    'accepted'              => ':attribute musí být akceptován.',
    'active_url'            => ':attribute není platnou URL adresou.',
    'after'                 => ':attribute musí být datum po :date.',
    'alpha'                 => ':attribute může obsahovat pouze písmena.',
    'alpha_dash'            => ':attribute může obsahovat pouze písmena, číslice, pomlčky a podtržítka. České znaky (á, é, í, ó, ú, ů, ž, š, č, ř, ď, ť, ň) nejsou podporovány.',
    'alpha_num'             => ':attribute může obsahovat pouze písmena a číslice.',
    'array'                 => ':attribute musí být pole.',
    'before'                => ':attribute musí být datum před :date.',
    'between'               => [
        'array'     => ':attribute musí obsahovat nejméně :min a nesmí obsahovat více než :max prvků.',
        'file'      => ':attribute musí být větší než :min a menší než :max Kilobytů.',
        'numeric'   => ':attribute musí být hodnota mezi :min a :max.',
        'string'    => ':attribute musí být delší než :min a kratší než :max znaků.',
    ],
    'boolean'               => 'The :attribute field must be true or false',
    'confirmed'             => ':attribute nebylo odsouhlaseno.',
    'custom'                => [
        'attribute-name'    => [
            'rule-name' => 'custom-message',
        ],
    ],
    'date'                  => ':attribute musí být platné datum.',
    'date_format'           => ':attribute není platný formát data podle :format.',
    'different'             => ':attribute a :other se musí lišit.',
    'digits'                => ':attribute musí být :digits pozic dlouhé.',
    'digits_between'        => ':attribute musí být dlouhé nejméně :min a nejvíce :max pozic.',
    'email'                 => ':attribute není platný formát.',
    'exists'                => 'Zvolená hodnota pro :attribute není platná.',
    'filled'                => ':attribute musí být vyplněno.',
    'image'                 => ':attribute musí být obrázek.',
    'in'                    => 'Zvolená hodnota pro :attribute není platná.',
    'integer'               => ':attribute musí být celé číslo.',
    'ip'                    => ':attribute musí být platnou IP adresou.',
    'json'                  => 'The :attribute must be a valid JSON string.',
    'max'                   => [
        'array'     => ':attribute nesmí obsahovat více než :max prvků.',
        'file'      => ':attribute musí být menší než :max Kilobytů.',
        'numeric'   => ':attribute musí být nižší než :max.',
        'string'    => ':attribute musí být kratší než :max znaků.',
    ],
    'mimes'                 => ':attribute musí být jeden z následujících datových typů :values.',
    'min'                   => [
        'array'     => ':attribute musí obsahovat více než :min prvků.',
        'file'      => ':attribute musí být větší než :min Kilobytů.',
        'numeric'   => ':attribute musí být větší než :min.',
        'string'    => ':attribute musí být delší než :min znaků.',
    ],
    'not_in'                => 'Zvolená hodnota pro :attribute je neplatná.',
    'numeric'               => ':attribute musí být číslo.',
    'regex'                 => ':attribute nemá správný formát.',
    'required'              => ':attribute musí být vyplněno.',
    'required_if'           => ':attribute musí být vyplněno pokud :other je :value.',
    'required_unless'       => 'The :attribute field is required unless :other is in :value.',
    'required_with'         => ':attribute musí být vyplněno pokud :values je zvoleno.',
    'required_with_all'     => 'The :attribute field is required when :values is present.',
    'required_without'      => ':attribute musí být vyplněno pokud :values není vyplněno.',
    'required_without_all'  => 'The :attribute field is required when none of :values are present.',
    'same'                  => ':attribute a :other se musí shodovat.',
    'size'                  => [
        'array'     => ':attribute musí obsahovat právě :size prvků.',
        'file'      => ':attribute musí mít přesně :size Kilobytů.',
        'numeric'   => ':attribute musí být přesně :size.',
        'string'    => ':attribute musí být přesně :size znaků dlouhý.',
    ],
    'string'                => 'The :attribute must be a string.',
    'timezone'              => 'The :attribute must be a valid zone.',
    'unique'                => ':attribute musí být unikátní.',
    'url'                   => 'Formát :attribute je neplatný.',
];
