<?php

return [
    'accepted'              => ':attribute muss akzeptiert werden.',
    'active_url'            => ':attribute ist keine gültige Internet-Adresse.',
    'after'                 => ':attribute muss ein Datum nach dem :date sein.',
    'alpha'                 => ':attribute darf nur aus Buchstaben bestehen.',
    'alpha_dash'            => ':attribute darf nur aus Buchstaben, Zahlen, Binde- und Unterstrichen bestehen. Umlaute (ä, ö, ü) und Eszett (ß) sind nicht erlaubt.',
    'alpha_num'             => ':attribute darf nur aus Buchstaben und Zahlen bestehen.',
    'array'                 => ':attribute muss ein Array sein.',
    'before'                => ':attribute muss ein Datum vor dem :date sein.',
    'between'               => [
        'array'     => ':attribute muss zwischen :min & :max Elemente haben.',
        'file'      => ':attribute muss zwischen :min & :max Kilobytes groß sein.',
        'numeric'   => ':attribute muss zwischen :min & :max liegen.',
        'string'    => ':attribute muss zwischen :min & :max Zeichen lang sein.',
    ],
    'boolean'               => ':attribute muss entweder \'true\' oder \'false\' sein.',
    'confirmed'             => ':attribute stimmt nicht mit der Bestätigung überein.',
    'date'                  => ':attribute muss ein gültiges Datum sein.',
    'date_format'           => ':attribute entspricht nicht dem gültigen Format für :format.',
    'different'             => ':attribute und :other müssen sich unterscheiden.',
    'digits'                => ':attribute muss :digits Stellen haben.',
    'digits_between'        => ':attribute muss zwischen :min und :max Stellen haben.',
    'email'                 => ':attribute Format ist ungültig.',
    'exists'                => 'Der gewählte Wert für :attribute ist ungültig.',
    'filled'                => ':attribute muss ausgefüllt sein.',
    'image'                 => ':attribute muss ein Bild sein.',
    'in'                    => 'Der gewählte Wert für :attribute ist ungültig.',
    'integer'               => ':attribute muss eine ganze Zahl sein.',
    'ip'                    => ':attribute muss eine gültige IP-Adresse sein.',
    'json'                  => 'The :attribute must be a valid JSON string.',
    'max'                   => [
        'array'     => ':attribute darf nicht mehr als :max Elemente haben.',
        'file'      => ':attribute darf maximal :max Kilobytes groß sein.',
        'numeric'   => ':attribute darf maximal :max sein.',
        'string'    => ':attribute darf maximal :max Zeichen haben.',
    ],
    'mimes'                 => ':attribute muss den Dateityp :values haben.',
    'min'                   => [
        'array'     => ':attribute muss mindestens :min Elemente haben.',
        'file'      => ':attribute muss mindestens :min Kilobytes groß sein.',
        'numeric'   => ':attribute muss mindestens :min sein.',
        'string'    => ':attribute muss mindestens :min Zeichen lang sein.',
    ],
    'not_in'                => 'Der gewählte Wert für :attribute ist ungültig.',
    'numeric'               => ':attribute muss eine Zahl sein.',
    'regex'                 => ':attribute Format ist ungültig.',
    'required'              => ':attribute muss ausgefüllt sein.',
    'required_if'           => ':attribute muss ausgefüllt sein wenn :other :value ist.',
    'required_unless'       => 'The :attribute field is required unless :other is in :value.',
    'required_with'         => ':attribute muss angegeben werden wenn :values ausgefüllt wurde.',
    'required_with_all'     => ':attribute muss angegeben werden, wenn :values ausgefüllt wurde.',
    'required_without'      => ':attribute muss angegeben werden wenn :values nicht ausgefüllt wurde.',
    'required_without_all'  => ':attribute muss angegeben werden wenn keines der Felder :values ausgefüllt wurde.',
    'same'                  => ':attribute und :other müssen übereinstimmen.',
    'size'                  => [
        'numeric'   => ':attribute muss gleich :size sein.',
    ],
];
