<?php

return [
    'accepted'              => 'Rhaid derbyn :attribute.',
    'active_url'            => 'Nid yw :attribute yn URL dilys.',
    'after'                 => 'Rhaid i :attribute fod yn ddyddiad sydd ar ôl :date.',
    'alpha'                 => 'Dim ond llythrennau\'n unig gall :attribute gynnwys.',
    'alpha_dash'            => 'Dim ond llythrennau, rhifau a dash yn unig gall :attribute gynnwys.',
    'alpha_num'             => 'Dim ond llythrennau a rhifau yn unig gall :attribute gynnwys.',
    'array'                 => 'Rhaid i :attribute fod yn array.',
    'before'                => 'Rhaid i :attribute fod yn ddyddiad sydd cyn :date.',
    'between'               => [
        'array'     => 'Rhaid i :attribute fod rhwng :min a :max eitem.',
        'file'      => 'Rhaid i :attribute fod rhwng :min a :max kilobytes.',
        'numeric'   => 'Rhaid i :attribute fod rhwng :min a :max.',
        'string'    => 'Rhaid i :attribute fod rhwng :min a :max nodyn.',
    ],
    'boolean'               => 'Rhaid i\'r maes :attribute fod yn wir neu gau.',
    'confirmed'             => 'Nid yw\'r cadarnhad :attribute yn gyfwerth.',
    'custom'                => [
        'attribute-name'    => [
            'rule-name' => 'custom-message',
        ],
    ],
    'date'                  => 'Nid yw :attribute yn ddyddiad dilys.',
    'date_format'           => 'Nid yw :attribute yn y fformat :format.',
    'different'             => 'Rhaid i :attribute a :other fod yn wahanol.',
    'digits'                => 'Rhaid i :attribute fod yn :digits digid.',
    'digits_between'        => 'Rhaid i :attribute fod rhwng :min a :max digid.',
    'email'                 => 'Rhaid i :attribute fod yn gyfeiriad ebost dilys.',
    'exists'                => 'Nid yw :attribute yn ddilys.',
    'filled'                => 'Rhaid cynnwys :attribute.',
    'image'                 => 'Rhaid i :attribute fod yn lun.',
    'in'                    => 'Nid yw :attribute yn ddilys.',
    'integer'               => 'Rhaid i :attribute fod yn integer.',
    'ip'                    => 'Rhaid i :attribute fod yn gyfeiriad IP dilys.',
    'json'                  => 'The :attribute must be a valid JSON string.',
    'max'                   => [
        'array'     => 'Ni chai :attribute fod yn fwy na :max eitem.',
        'file'      => 'Ni chai :attribute fod yn fwy na :max kilobytes.',
        'numeric'   => 'Ni chai :attribute fod yn fwy na :max.',
        'string'    => 'Ni chai :attribute fod yn fwy na :max nodyn.',
    ],
    'mimes'                 => 'Rhaid i :attribute fod yn ffeil o\'r math: :values.',
    'min'                   => [
        'array'     => 'Rhaid i :attribute fod o leiaf :min eitem.',
        'file'      => 'Rhaid i :attribute fod o leiaf :min kilobytes.',
        'numeric'   => 'Rhaid i :attribute fod o leiaf :min.',
        'string'    => 'Rhaid i :attribute fod o leiaf :min nodyn.',
    ],
    'not_in'                => 'Nid yw :attribute yn ddilys.',
    'numeric'               => 'Rhaid i :attribute fod yn rif.',
    'regex'                 => 'Nid yw fformat :attribute yn ddilys.',
    'required'              => 'Rhaid cynnwys :attribute.',
    'required_if'           => 'Rhaid cynnwys :attribute pan mae :other yn :value.',
    'required_unless'       => 'The :attribute field is required unless :other is in :value.',
    'required_with'         => 'Rhaid cynnwys :attribute pan mae :values yn bresennol.',
    'required_with_all'     => 'Rhaid cynnwys :attribute pan mae :values yn bresennol.',
    'required_without'      => 'Rhaid cynnwys :attribute pan nad oes :values yn bresennol.',
    'required_without_all'  => 'Rhaid cynnwys :attribute pan nad oes :values yn bresennol.',
    'same'                  => 'Rhaid i :attribute a :other fod yn gyfwerth.',
    'size'                  => [
        'array'     => 'Rhaid i :attribute fod yn :size eitem.',
        'file'      => 'Rhaid i :attribute fod yn :size kilobytes.',
        'numeric'   => 'Rhaid i :attribute fod yn :size.',
        'string'    => 'Rhaid i :attribute fod yn :size nodyn.',
    ],
    'string'                => 'The :attribute must be a string.',
    'timezone'              => 'Rhaid i :attribute fod yn timezone dilys.',
    'unique'                => 'Mae :attribute eisoes yn bodoli.',
    'url'                   => 'Nid yw fformat :attribute yn ddilys.',
];
