<?php

return [
    'accepted'              => 'Polje :attribute mora biti prihvaćeno.',
    'active_url'            => 'Polje :attribute nije validan URL.',
    'after'                 => 'Polje :attribute mora biti datum poslije :date.',
    'alpha'                 => 'Polje :attribute može sadržati samo slova.',
    'alpha_dash'            => 'Polje :attribute može sadržati samo slova, brojeve i povlake.',
    'alpha_num'             => 'Polje :attribute može sadržati samo slova i brojeve.',
    'array'                 => 'Polje :attribute mora biti niz.',
    'before'                => 'Polje :attribute mora biti datum prije :date.',
    'between'               => [
        'array'     => 'Polje :attribute mora biti između :min - :max karaktera.',
        'file'      => 'Fajl :attribute mora biti izmedju :min - :max kilobajta.',
        'numeric'   => 'Polje :attribute mora biti izmedju :min - :max.',
        'string'    => 'Polje :attribute mora biti izmedju :min - :max karaktera.',
    ],
    'boolean'               => 'Polje :attribute mora biti tačno ili netačno',
    'confirmed'             => 'Potvrda polja :attribute se ne poklapa.',
    'custom'                => [
        'attribute-name'    => [
            'rule-name' => 'custom-message',
        ],
    ],
    'date'                  => 'Polje :attribute nema ispravan datum.',
    'date_format'           => 'Polje :attribute nema odgovarajući format :format.',
    'different'             => 'Polja :attribute i :other moraju biti različita.',
    'digits'                => 'Polje :attribute mora da sadži :digits brojeve.',
    'digits_between'        => 'Polje :attribute mora biti između :min i :max broja.',
    'email'                 => 'Format polja :attribute mora biti validan email.',
    'exists'                => 'Odabrano polje :attribute nije validno.',
    'filled'                => 'Polje :attribute je obavezno.',
    'image'                 => 'Polje :attribute mora biti slika.',
    'in'                    => 'Odabrano polje :attribute nije validno.',
    'integer'               => 'Polje :attribute mora biti broj.',
    'ip'                    => 'Polje :attribute mora biti validna IP adresa.',
    'json'                  => 'The :attribute must be a valid JSON string.',
    'max'                   => [
        'array'     => 'Polje :attribute mora sadržati manje od :max karaktera.',
        'file'      => 'Polje :attribute mora biti manje od :max kilobajta.',
        'numeric'   => 'Polje :attribute mora biti manje od :max.',
        'string'    => 'Polje :attribute mora sadržati manje od :max karaktera.',
    ],
    'mimes'                 => 'Polje :attribute mora biti fajl tipa: :values.',
    'min'                   => [
        'array'     => 'Polje :attribute mora sadržati najmanje :min karaktera.',
        'file'      => 'Fajl :attribute mora biti najmanje :min kilobajta.',
        'numeric'   => 'Polje :attribute mora biti najmanje :min.',
        'string'    => 'Polje :attribute mora sadržati najmanje :min karaktera.',
    ],
    'not_in'                => 'Odabrani element polja :attribute nije validan.',
    'numeric'               => 'Polje :attribute mora biti broj.',
    'regex'                 => 'Polje :attribute ima neispravan format.',
    'required'              => 'Polje :attribute je obavezno.',
    'required_if'           => 'Polje :attribute je obavezno kada :other je :value.',
    'required_unless'       => 'The :attribute field is required unless :other is in :value.',
    'required_with'         => 'Polje :attribute je obavezno kada je :values prikazano.',
    'required_with_all'     => 'Polje :attribute je obavezno kada je :values prikazano.',
    'required_without'      => 'Polje :attribute je obavezno kada :values nije prikazano.',
    'required_without_all'  => 'Polje :attribute je obavezno kada nijedno :values nije prikazano.',
    'same'                  => 'Polja :attribute i :other se moraju poklapati.',
    'size'                  => [
        'array'     => 'Polje :attribute mora biti :size karaktera.',
        'file'      => 'Fajl :attribute mora biti :size kilobajta.',
        'numeric'   => 'Polje :attribute mora biti :size.',
        'string'    => 'Polje :attribute mora biti :size karaktera.',
    ],
    'string'                => 'Polje :attribute mora sadrzavati slova.',
    'timezone'              => 'Polje :attribute mora biti ispravna vremenska zona.',
    'unique'                => 'Polje :attribute već postoji.',
    'url'                   => 'Format polja :attribute nije validan.',
];
