<?php

return [
    'use_smtp'          => 'Brug SMTP -',
    'use_sparkpost'     => 'Brug Sparkpost',
    'user_access'       => 'Adgang Og Tilladelser',
    'user_create_event' => 'Der er tilføjet en ny bruger, der er identificeret af :email',
    'user_created'      => 'Bruger-konto er blevet oprettet',
    'user_roles'        => 'Brugerroller',
    'userame'           => 'Brugernavn',
    'username'          => 'Brugernavn',
    'username_email'    => 'Brugernavn eller e-Mail',
    'users'             => 'Brugere',
    'verdict'           => 'Dommen',
    'view'              => 'Udsigt',
    'view_attendance'   => 'Se Deltagerliste',
    'view_payments'     => 'Udsigt Betalinger',
    'view_profile'      => 'Vis Profil',
    'view_results'      => 'Se Resultater',
    'view_students'     => 'Udsigt Studerende',
    'view_subjects'     => 'Vis Emner',
    'view_timetable'    => 'Se Tidsplan',
    'weeks'             => ':n Uger',
    'with_rooms'        => 'Værelser',
    'year'              => 'År',
    'year_of_pub'       => 'Udgivelsesår',
    'yearly_overview'   => 'Årlig Oversigt',
    'years'             => ':n År',
    'yes'               => 'Ja',
    'yes_continue'      => 'Ja Fortsætte',
    'your_f_name'       => 'Elevens Første Navn',
    'your_l_name'       => 'Elevens efternavn',
    'your_marks'        => 'Mærker Nået til',
    'your_sir_name'     => 'Elevens Efternavn',
];
