<?php

return [
    'accepted'              => ':attribute skal accepteres.',
    'active_url'            => ':attribute er ikke en valid URL.',
    'after'                 => ':attribute skal være en dato efter :date.',
    'alpha'                 => ':attribute må kun bestå af bogstaver.',
    'alpha_dash'            => ':attribute må kun bestå af bogstaver, tal og bindestreger.',
    'alpha_num'             => ':attribute må kun bestå af bogstaver og tal.',
    'array'                 => ':attribute skal være et array.',
    'before'                => ':attribute skal være en dato før :date.',
    'between'               => [
        'array'     => ':attribute skal indeholde mellem :min - :max elementer.',
        'file'      => ':attribute skal være imellem :min - :max kilobytes.',
        'numeric'   => ':attribute skal være imellem :min - :max.',
        'string'    => ':attribute skal være imellem :min - :max tegn.',
    ],
    'boolean'               => ':attribute skal være sandt eller falsk',
    'confirmed'             => ':attribute er ikke det samme som bekræftelsesfeltet.',
    'custom'                => [
        'attribute-name'    => [
            'rule-name' => 'custom-message',
        ],
    ],
    'date'                  => ':attribute er ikke en gyldig dato.',
    'date_format'           => ':attribute matcher ikke formatet :format.',
    'different'             => ':attribute og :other skal være forskellige.',
    'digits'                => ':attribute skal have :digits cifre.',
    'digits_between'        => ':attribute skal have mellem :min og :max cifre.',
    'email'                 => ':attribute skal være en gyldig e-mailadresse.',
    'exists'                => 'Det valgte :attribute er ugyldig.',
    'filled'                => ':attribute skal udfyldes.',
    'image'                 => ':attribute skal være et billede.',
    'in'                    => 'Det valgte :attribute er ugyldig.',
    'integer'               => ':attribute skal være et heltal.',
    'ip'                    => ':attribute skal være en gyldig IP adresse.',
    'json'                  => ':attribute skal være en gyldig JSON streng.',
    'max'                   => [
        'array'     => ':attribute må ikke indeholde mere end :max elementer.',
        'file'      => ':attribute skal være højest :max kilobytes.',
        'numeric'   => ':attribute skal være højest :max.',
        'string'    => ':attribute skal være højest :max tegn.',
    ],
    'mimes'                 => ':attribute skal være en fil af typen: :values.',
    'min'                   => [
        'array'     => ':attribute skal indeholde mindst :min elementer.',
        'file'      => ':attribute skal være mindst :min kilobytes.',
        'numeric'   => ':attribute skal være mindst :min.',
        'string'    => ':attribute skal være mindst :min tegn.',
    ],
    'not_in'                => 'Den valgte :attribute er ugyldig.',
    'numeric'               => ':attribute skal være et tal.',
    'regex'                 => ':attribute formatet er ugyldigt.',
    'required'              => ':attribute skal udfyldes.',
    'required_if'           => ':attribute skal udfyldes når :other er :value.',
    'required_unless'       => 'The :attribute field is required unless :other is in :value.',
    'required_with'         => ':attribute skal udfyldes når :values er udfyldt.',
    'required_with_all'     => ':attribute skal udfyldes når :values er udfyldt.',
    'required_without'      => ':attribute skal udfyldes når :values ikke er udfyldt.',
    'required_without_all'  => ':attribute skal udfyldes når ingen af :values er udfyldt.',
    'same'                  => ':attribute og :other skal være ens.',
    'size'                  => [
        'array'     => ':attribute skal indeholde :size elementer.',
        'file'      => ':attribute skal være :size kilobytes.',
        'numeric'   => ':attribute skal være :size.',
        'string'    => ':attribute skal være :size tegn lang.',
    ],
    'string'                => 'The :attribute must be a string.',
    'timezone'              => 'The :attribute must be a valid zone.',
    'unique'                => ':attribute er allerede taget.',
    'url'                   => ':attribute formatet er ugyldigt.',
];
