<?php

return [
    'accepted'              => 'Трябва да приемете :attribute.',
    'active_url'            => 'Полето :attribute не е валиден URL адрес.',
    'after'                 => 'Полето :attribute трябва да бъде дата след :date.',
    'alpha'                 => 'Полето :attribute трябва да съдържа само букви.',
    'alpha_dash'            => 'Полето :attribute трябва да съдържа само букви, цифри, долна черта и тире.',
    'alpha_num'             => 'Полето :attribute трябва да съдържа само букви и цифри.',
    'array'                 => 'Полето :attribute трябва да бъде масив.',
    'attributes'            => [
        'address'                   => 'Адрес',
        'age'                       => 'Възраст',
        'available'                 => 'Достъпен',
        'city'                      => 'Град',
        'content'                   => 'Съдържание',
        'country'                   => 'Държава',
        'date'                      => 'Дата',
        'day'                       => 'Ден',
        'description'               => 'Описание',
        'email'                     => 'E-mail',
        'excerpt'                   => 'Откъс',
        'first_name'                => 'Име',
        'gender'                    => 'Пол',
        'hour'                      => 'Час',
        'last_name'                 => 'Фамилия',
        'message'                   => 'Съобщение',
        'minute'                    => 'Минута',
        'mobile'                    => 'GSM',
        'month'                     => 'Месец',
        'name'                      => 'Име',
        'password'                  => 'Парола',
        'phone'                     => 'Телефон',
        'recaptcha_response_field'  => 'Рекапча',
        'second'                    => 'Секунда',
        'sex'                       => 'Пол',
        'size'                      => 'Размер',
        'subject'                   => 'Заглавие',
        'time'                      => 'Време',
        'title'                     => 'Заглавие',
        'username'                  => 'Потребител',
        'year'                      => 'Година',
    ],
    'before'                => 'Полето :attribute трябва да бъде дата преди :date.',
    'between'               => [
        'array'     => 'Полето :attribute трябва да има между :min - :max елемента.',
        'file'      => 'Полето :attribute трябва да бъде между :min и :max килобайта.',
        'numeric'   => 'Полето :attribute трябва да бъде между :min и :max.',
        'string'    => 'Полето :attribute трябва да бъде между :min и :max знака.',
    ],
    'boolean'               => 'Полето :attribute трябва да съдържа Да или Не',
    'confirmed'             => 'Полето :attribute не е потвърдено.',
    'custom'                => [
        'attribute-name'    => [
            'rule-name' => 'custom-message',
        ],
    ],
    'date'                  => 'Полето :attribute не е валидна дата.',
    'date_format'           => 'Полето :attribute не е във формат :format.',
    'different'             => 'Полетата :attribute и :other трябва да са различни.',
    'digits'                => 'Полето :attribute трябва да има :digits цифри.',
    'digits_between'        => 'Полето :attribute трябва да има между :min и :max цифри.',
    'email'                 => 'Полето :attribute е в невалиден формат.',
    'exists'                => 'Избранато поле :attribute вече съществува.',
    'filled'                => 'Полето :attribute е задължително.',
    'image'                 => 'Полето :attribute трябва да бъде изображение.',
    'in'                    => 'Избраното поле :attribute е невалидно.',
    'integer'               => 'Полето :attribute трябва да бъде цяло число.',
    'ip'                    => 'Полето :attribute трябва да бъде IP адрес.',
    'json'                  => 'Полето :attribute трябва да бъде JSON низ.',
    'max'                   => [
        'array'     => 'Полето :attribute трябва да има по-малко от :max елемента.',
        'file'      => 'Полето :attribute трябва да бъде по-малко от :max килобайта.',
        'numeric'   => 'Полето :attribute трябва да бъде по-малко от :max.',
        'string'    => 'Полето :attribute трябва да бъде по-малко от :max знака.',
    ],
    'mimes'                 => 'Полето :attribute трябва да бъде файл от тип: :values.',
    'min'                   => [
        'array'     => 'Полето :attribute трябва има минимум :min елемента.',
        'file'      => 'Полето :attribute трябва да бъде минимум :min килобайта.',
        'numeric'   => 'Полето :attribute трябва да бъде минимум :min.',
        'string'    => 'Полето :attribute трябва да бъде минимум :min знака.',
    ],
    'not_in'                => 'Избраното поле :attribute е невалидно.',
    'numeric'               => 'Полето :attribute трябва да бъде число.',
    'regex'                 => 'Полето :attribute е в невалиден формат.',
    'required'              => 'Полето :attribute е задължително.',
    'required_if'           => 'Полето :attribute се изисква, когато :other е :value.',
    'required_unless'       => 'The :attribute field is required unless :other is in :value.',
    'required_with'         => 'Полето :attribute се изисква, когато :values има стойност.',
    'required_with_all'     => 'Полето :attribute е задължително, когато :values имат стойност.',
    'required_without'      => 'Полето :attribute се изисква, когато :values няма стойност.',
    'required_without_all'  => 'Полето :attribute се изисква, когато никое от полетата :values няма стойност.',
    'same'                  => 'Полетата :attribute и :other трябва да съвпадат.',
    'size'                  => [
        'array'     => 'Полето :attribute трябва да има :size елемента.',
        'file'      => 'Полето :attribute трябва да бъде :size килобайта.',
        'numeric'   => 'Полето :attribute трябва да бъде :size.',
        'string'    => 'Полето :attribute трябва да бъде :size знака.',
    ],
    'string'                => 'Полето :attribute трябва да бъде знаков низ.',
    'timezone'              => 'Полето :attribute трябва да съдържа валидна часова зона.',
    'unique'                => 'Полето :attribute вече съществува.',
    'url'                   => 'Полето :attribute е в невалиден формат.',
];
